
language: python
python: 2.7
env:
  - TOX_ENV=py27
  - TOX_ENV=docs
  - TOX_ENV=style
install:
  - pip install tox
  - pip install python-coveralls
script:
  - tox -e $TOX_ENV
after_success:
  - coveralls -d tests/.coverage
